import {test, expect, chromium} from '@playwright/test';
import path from 'node:path';
test('loads as a real extension, saves settings, and handles missing credentials', async () => {
  const extension = path.resolve('extension');
  const context = await chromium.launchPersistentContext('', {headless: true, channel: 'chromium', args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`]});
  try {
    const worker = context.serviceWorkers()[0] || await context.waitForEvent('serviceworker');
    const id = new URL(worker.url()).host;
    const options = await context.newPage();
    await options.goto(`chrome-extension://${id}/options.html`);
    await expect(options.locator('.card')).toHaveCount(6);
    await options.getByRole('button',{name:'mu.social',exact:true}).click();
    await expect(options.locator('#site-domain')).toHaveValue('mu.social');
    await options.locator('#site-domain').fill('');
    await expect(options.locator('#site-domain')).not.toHaveAttribute('list');
    await options.locator('.sites-section').screenshot({path:'test-results/site-suggestions.png'});
    await expect(options.getByLabel('Enable filters',{exact:true})).not.toBeChecked();
    await expect(options.locator('.rule-action')).toHaveValue('blur');
    await expect(options.locator('.rule-label')).toHaveValue('Hostile');
    await options.getByRole('button',{name:'Remove rule',exact:true}).click();
    await options.getByLabel('Live classification').uncheck();
    await options.getByRole('button', {name: 'Save settings'}).click();
    await expect(options.locator('#status')).toContainText('Saved');
    await options.reload();
    await expect(options.getByLabel('Live classification')).not.toBeChecked();
    await options.getByLabel('Live classification').check();
    await options.getByRole('button', {name: 'Save settings'}).click();
    await expect(options.locator('#status')).toContainText('Saved');
    await options.getByRole('button', {name:'Add classifier'}).click();
    await options.locator('.custom-name').fill('Humor');
    await options.locator('.custom-question').fill('What kind of humor does this post use?');
    await options.locator('.custom-labels').fill('Dry humor');
    await options.getByRole('button', {name:'Save settings'}).click();
    await expect(options.locator('#status')).toContainText('2–12 labels');
    await options.locator('.custom-labels').fill('Dry humor\nWordplay\nNot humorous');
    await options.getByRole('button', {name:'Save settings'}).click();
    await expect(options.locator('#status')).toHaveText('Saved.');
    await options.reload();
    await expect(options.locator('.custom-name')).toHaveValue('Humor');
    await expect(options.locator('.custom-enabled')).toBeChecked();
    await options.locator('.custom-enabled').uncheck();
    await options.getByRole('button', {name:'Save settings'}).click();
    await expect(options.locator('#status')).toHaveText('Saved.');
    await options.reload();
    await expect(options.locator('.custom-enabled')).not.toBeChecked();
    await options.getByRole('button', {name:'Remove', exact:true}).click();
    await options.getByRole('button', {name:'Save settings'}).click();
    await expect(options.locator('#status')).toHaveText('Saved.');
    await options.reload();
    await expect(options.locator('.custom')).toHaveCount(0);
    await options.getByRole('button',{name:'Add rule',exact:true}).click();
    await expect(options.locator('.rule-action')).toHaveValue('blur');
    await options.getByLabel('Enable filters',{exact:true}).check();
    await options.locator('.rule-action').selectOption('hide');
    await options.getByRole('button',{name:'Save settings'}).click();
    await expect(options.locator('#status')).toHaveText('Saved.');
    await options.reload();
    await expect(options.locator('.rule-action')).toHaveValue('hide');
    await expect(options.getByLabel('Enable filters',{exact:true})).toBeChecked();
    await options.screenshot({path: 'test-results/settings.png', fullPage: true});
    const page = await context.newPage();
    await page.route('https://bsky.app/**', route => route.fulfill({contentType: 'text/html', body: '<html><body style="background:#161e2a;color:white;font:18px system-ui;padding:60px"><div data-testid="composePostView" style="max-width:620px;margin:auto"><h2>New post</h2><div><div class="tiptap" role="textbox" contenteditable="true" style="min-height:180px"></div></div></div></body></html>'}));
    await page.goto('https://bsky.app/');
    await page.getByRole('textbox').fill('Thanks for explaining this!');
    await expect(page.locator('.labels')).toContainText('Add your TypeSafe API key');
    await page.screenshot({path: 'test-results/composer.png', fullPage: true});
    // Test the real worker and storage listener with a mocked API, never a live key.
    await worker.evaluate(async()=>{
      globalThis.fetch=async(_url,options)=>{
        const request=JSON.parse(options.body);
        const answers=Object.fromEntries(Object.entries(request.questions).map(([id,q])=>{const choice=Object.keys(q.criteria)[0];return [id,{type:'choice',choice,confidence:.9,probabilities:{[choice]:.95}}];}));
        return new Response(JSON.stringify({answers,usage:{input_tokens:1000000,output_tokens:100}}),{status:200,headers:{'Content-Type':'application/json'}});
      };
      await chrome.storage.local.set({apiKey:'test-only-fake-key'});
    });
    await page.getByRole('textbox').fill('Another draft for testing');
    await expect(page.locator('.chip')).toHaveCount(6);
    await expect(options.locator('[data-stat="requests"]')).toHaveText('1');
    await expect(options.locator('[data-stat="successful"]')).toHaveText('1');
    await expect(options.locator('[data-stat="cost"]')).toHaveText('$0.042000');
    await options.reload();
    await expect(options.locator('[data-stat="decisions"]')).toHaveText('6');
    await options.screenshot({path:'test-results/settings-with-usage.png',fullPage:true});
    // Exercise dynamic registration with an already-granted test origin; no permission prompt or network call.
    await options.evaluate(async()=>{
      await chrome.storage.local.set({sites:[{origin:'https://api.typesafe.ai',postSelector:'',composerSelector:''}]});
      const {syncSites}=await import('./sites.js');await syncSites();await syncSites();
    });
    const registered=await options.evaluate(()=>chrome.scripting.getRegisteredContentScripts());
    expect(registered[0].js).toEqual(['filters.js','content.js','posts.js']);
    const addedSite=await context.newPage();
    await addedSite.route('https://api.typesafe.ai/**',route=>route.fulfill({contentType:'text/html',body:'<div data-testid="composePostView"><div class="tiptap" contenteditable="true" role="textbox"></div></div>'}));
    await addedSite.goto('https://api.typesafe.ai/test-extension-loading');
    await addedSite.getByRole('textbox').fill('Dynamic registration test');
    await expect(addedSite.locator('.chip')).toHaveCount(6);
    await worker.evaluate(()=>chrome.storage.local.set({usagePricing:null}));
    await options.reload();
    await expect(options.locator('#input-rate')).toHaveValue('0.042');
    await expect(options.locator('#output-rate')).toHaveValue('0');
    await options.getByRole('button',{name:'Clear stats',exact:true}).click();
    await expect(options.locator('#clear-stats-status')).toHaveText('Stats cleared. Settings and API key kept.');
    await expect(options.locator('[data-stat="requests"]')).toHaveText('0');
    await expect(options.locator('[data-stat="cost"]')).toHaveText('$0.000000');
    await options.reload();
    await expect(options.locator('[data-stat="decisions"]')).toHaveText('0');
    await expect(options.locator('#apiKey')).toHaveValue('test-only-fake-key');
    await expect(options.getByLabel('Enable filters',{exact:true})).toBeChecked();
    await expect(options.getByRole('heading',{name:'Jevibe Check',exact:true})).toBeVisible();
    await addedSite.getByRole('textbox').fill('A fresh request after resetting stats');
    await expect(options.locator('[data-stat="requests"]')).toHaveText('1');
    await expect(options.locator('[data-stat="successful"]')).toHaveText('1');

    const customFeed=await context.newPage();
    await customFeed.route('https://bsky.app/**',route=>route.fulfill({contentType:'text/html',body:'<main data-testid="customFeedScreen"><div data-testid="feedItem-by-example.com"><div data-testid="contentHider-post"><div data-testid="postText" data-word-wrap="1">Thanks for building on AT Protocol</div></div></div></main>'}));
    await customFeed.goto('https://bsky.app/profile/example.test/feed/test');
    await expect(customFeed.locator('[data-darter-post] .chip, [data-darter-post] .labels span')).toHaveCount(6);
  } finally {await context.close();}
});
